apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: mysql-pass-d2gtcm2t2k
type: Opaque
data:
  # My customized password is "my very complicated password".
  password: bXkgdmVyeSBjb21wbGljYXRlZCBwYXNzd29yZAo=
