apiVersion: manifest.k8s.io/v1alpha1
kind: Manifest
metadata:
  name: mysql
description: |
  MySQL Deployment using GCE persistent-volume.
  You need to create the disk in GCE, potentially by running:
    gcloud compute disks create --size=500GB --zone=us-central1-a mysql-persistent-storage
resources:
- ../emptyDir
patches:
- volume.yaml
